version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.0
    - 2.32.1
    - 2.32.10
    - 2.32.11
    - 2.32.2
    - 2.32.3
    - 2.32.4
    - 2.32.7
    - 2.32.8
    - 2.32.9
  - dependency-name: gatsby-plugin-less
    versions:
    - 4.6.0
    - 4.7.0
  - dependency-name: gatsby-transformer-remark
    versions:
    - 2.15.0
    - 2.16.0
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.10.0
    - 2.11.0
  - dependency-name: gatsby-plugin-netlify
    versions:
    - 2.10.0
    - 2.11.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.9.0
  - dependency-name: gatsby-plugin-google-analytics
    versions:
    - 2.10.0
  - dependency-name: gatsby-plugin-sass
    versions:
    - 2.8.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: jquery
    versions:
    - 3.5.1
  - dependency-name: lodash
    versions:
    - 4.17.20
